CREATE DATABASE IF NOT EXISTS BOOKSHOP;

CREATE SCHEMA IF NOT EXISTS BOOKSHOP.RAW;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.STAGGING;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.WAREHOUSE;
CREATE SCHEMA IF NOT EXISTS BOOKSHOP.MARTS;
