CREATE TABLE IF NOT EXISTS BOOKSHOP.RAW.CATEGORY (
    ID INTEGER,
    CODE VARCHAR,
    INTITULE VARCHAR
);

CREATE TABLE IF NOT EXISTS BOOKSHOP.RAW.BOOKS (
    ID INTEGER,
    CATEGORY_ID INTEGER,
    CODE VARCHAR,
    INTITULE VARCHAR,
    ISBN_10 VARCHAR,
    ISBN_13 VARCHAR,
    PRIX_CATALOGUE NUMBER(10,2)
);

CREATE TABLE IF NOT EXISTS BOOKSHOP.RAW.CUSTOMERS (
    ID INTEGER,
    CODE VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    EMAIL VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR
);

CREATE TABLE IF NOT EXISTS BOOKSHOP.RAW.FACTURES (
    ID INTEGER,
    CUSTOMER_ID INTEGER,
    CODE VARCHAR,
    QTE_TOTALE INTEGER,
    TOTAL_AMOUNT NUMBER(10,2),
    TOTAL_PAID NUMBER(10,2),
    DATE_EDIT VARCHAR
);

CREATE TABLE IF NOT EXISTS BOOKSHOP.RAW.VENTES (
    ID INTEGER,
    FACTURE_ID INTEGER,
    BOOK_ID INTEGER,
    PU NUMBER(10,2),
    QTE INTEGER,
    DATE_EDIT VARCHAR
);
